from typing import List
from fastapi import APIRouter, HTTPException, status
from google.cloud import firestore

from backend.app.db.firestore import get_firestore_client
from backend.app.schemas.recipe import RecipeGenerateRequest, AIRecipeResponse
from backend.app.services.ai_service import generate_recipe_from_ingredients
from datetime import datetime, timezone

router = APIRouter(prefix="/recipes", tags=["Recipes"])


def _get_db():
    db = get_firestore_client()
    if not db:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Firestore Database is not configured or disabled."
        )
    return db


@router.post("/generate", response_model=AIRecipeResponse)
async def generate_recipe(request: RecipeGenerateRequest):
    """
    The core AI endpoint. Takes a list of ingredients and returns a complete recipe.
    The recipe is generated by Google Gemini AI and returned to the frontend.
    """
    if not request.ingredients:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Please provide at least one ingredient."
        )

    # Call the AI service to generate the recipe
    ai_recipe = await generate_recipe_from_ingredients(request)

    # Bypass backend Firestore saving for local dev.
    # The frontend is already configured to save recipes directly to Firebase anyway!

    return ai_recipe


@router.get("/saved", response_model=List[dict])
def list_saved_recipes():
    """List all recipes that have been generated and saved previously."""
    db = _get_db()
    recipes = []
    # Note: requires an index in Firestore if we sort by created_at,
    # omitting the sort here to avoid requiring manual index creation for the hackathon
    docs = db.collection("recipes").limit(20).stream()
    
    for doc in docs:
        item = doc.to_dict()
        item["id"] = doc.id
        recipes.append(item)
    
    return recipes


@router.get("/saved/{recipe_id}", response_model=dict)
def get_saved_recipe(recipe_id: str):
    """Get a single saved recipe by its ID."""
    db = _get_db()
    doc_ref = db.collection("recipes").document(recipe_id)
    doc = doc_ref.get()
    
    if not doc.exists:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Recipe not found."
        )
        
    item = doc.to_dict()
    item["id"] = doc.id
    return item

